# Generated by Django 3.2.4 on 2021-06-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='neighbourhood',
            new_name='neighborhood',
        ),
    ]
