# Generated by Django 3.2.4 on 2021-06-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='name',
        ),
    ]
