# Generated by Django 3.2.4 on 2021-06-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_rename_business_name_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='health_tell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='police_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
