# Generated by Django 3.2.4 on 2021-06-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20210605_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='neighborhood_desc',
            field=models.TextField(),
        ),
    ]
